#!/usr/bin/env python3
"""Render generated Phase-3 API support artifacts."""

from __future__ import annotations

import json
import re
from typing import Any

from phase3.ui_locale import normalize_role_display_name


def camel_case(value: str) -> str:
    words = [part for part in re.split(r"[^A-Za-z0-9]+", value) if part]
    if not words:
        return "Generated"
    return "".join(word[:1].upper() + word[1:] for word in words)


def lower_camel(value: str) -> str:
    class_name = camel_case(value)
    if not class_name:
        return "handle"
    return class_name[:1].lower() + class_name[1:]


def runtime_spec_for_operation(
    operation: dict[str, str],
    operation_specs: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    operation_id = operation["operation_id"] or f"{operation['method']}-{operation['path']}"
    return operation_specs.get(operation_id, {})


def normalize_ui_role_name(value: Any, locale: str | None = None) -> str:
    candidate = re.sub(r"\s+", " ", str(value or "").strip().strip("`")).strip()
    if not candidate or locale is None:
        return candidate
    return normalize_role_display_name(candidate, locale) or candidate


def ordered_ui_roles(*groups: Any, locale: str | None = None) -> list[str]:
    ordered: list[str] = []
    seen: set[str] = set()
    for group in groups:
        items = group if isinstance(group, list) else [group]
        for item in items:
            role = normalize_ui_role_name(item, locale=locale)
            if not role:
                continue
            key = role.casefold()
            if key in seen:
                continue
            seen.add(key)
            ordered.append(role)
    return ordered


def split_ui_role_candidates(raw: Any, locale: str | None = None) -> list[str]:
    text = normalize_ui_role_name(raw, locale=locale).strip("[]")
    if not text or text.lower() in {"—", "-", "none", "n/a", "not_applicable"}:
        return []
    parts = [
        part.strip()
        for part in re.split(r"\s*(?:,|/|;|\||、|，|\band\b|\bor\b)\s*", text, flags=re.IGNORECASE)
        if part.strip()
    ]
    return ordered_ui_roles(parts or [text], locale=locale)


def extract_ui_policy_roles(raw: Any, locale: str | None = None) -> list[str]:
    text = normalize_ui_role_name(raw, locale=locale)
    if not text or text.lower() in {"—", "-", "none", "n/a", "not_applicable"}:
        return []
    bracketed: list[str] = []
    for match in re.findall(r"\[([^\]]+)\]", text):
        bracketed.extend(split_ui_role_candidates(match, locale=locale))
    if bracketed:
        return ordered_ui_roles(bracketed, locale=locale)
    simplified = re.sub(r"\b(?:role|roles|allow|allows|allowed|require|requires|required|policy|visible|visibility)\b", " ", text, flags=re.IGNORECASE)
    simplified = re.sub(r"\b(?:in|is|are|only|any|of|with|for|current|user|actor)\b", " ", simplified, flags=re.IGNORECASE)
    simplified = re.sub(r"\s+", " ", simplified).strip(" -:")
    return split_ui_role_candidates(simplified, locale=locale)


def render_runtime_adapter_module() -> str:
    return "\n".join(
        [
            "export interface GeneratedRuntimePayload {",
            "  path_params?: Record<string, unknown>;",
            "  pathParams?: Record<string, unknown>;",
            "  auth_context?: Record<string, unknown>;",
            "  authContext?: Record<string, unknown>;",
            "  body?: Record<string, unknown>;",
            "  query?: Record<string, unknown>;",
            "  force_error_code?: string;",
            "  invalid_query?: boolean;",
            "  [key: string]: unknown;",
            "}",
            "",
            "export type GeneratedRuntimeResult = Record<string, unknown>;",
            "",
            "function isRecord(value: unknown): value is Record<string, unknown> {",
            "  return typeof value === 'object' && value !== null && !Array.isArray(value);",
            "}",
            "",
            "function clonePayload<T>(value: T): T {",
            "  return JSON.parse(JSON.stringify(value)) as T;",
            "}",
            "",
            "function flattenNestedInputFields(target: Record<string, unknown>, value: unknown): void {",
            "  if (!isRecord(value)) {",
            "    return;",
            "  }",
            "  for (const [key, entry] of Object.entries(value)) {",
            "    if (target[key] === undefined) {",
            "      target[key] = clonePayload(entry);",
            "    }",
            "    if (isRecord(entry)) {",
            "      flattenNestedInputFields(target, entry);",
            "    }",
            "  }",
            "}",
            "",
            "export function normalizeGeneratedPayload(payload: GeneratedRuntimePayload): GeneratedRuntimePayload {",
            "  const next = isRecord(payload) ? clonePayload(payload) : {};",
            "  if (isRecord(next.body)) {",
            "    Object.assign(next, next.body);",
            "    delete next.body;",
            "  }",
            "  if (isRecord(next.input)) {",
            "    flattenNestedInputFields(next, next.input);",
            "  }",
            "  if (isRecord(next.query)) {",
            "    Object.assign(next, next.query);",
            "    delete next.query;",
            "  }",
            "  if (isRecord(next.pathParams) && !isRecord(next.path_params)) {",
            "    next.path_params = clonePayload(next.pathParams);",
            "  }",
            "  if (isRecord(next.authContext) && !isRecord(next.auth_context)) {",
            "    next.auth_context = clonePayload(next.authContext);",
            "  }",
            "  delete next.pathParams;",
            "  delete next.authContext;",
            "  return next as GeneratedRuntimePayload;",
            "}",
            "",
            "export function annotateRuntimePayload(",
            "  payload: GeneratedRuntimePayload,",
            "  additions: Record<string, unknown>,",
            "): GeneratedRuntimePayload {",
            "  const next = normalizeGeneratedPayload(payload);",
            "  for (const [key, value] of Object.entries(additions)) {",
            "    if (next[key] === undefined) {",
            "      next[key] = value;",
            "    }",
            "  }",
            "  return next;",
            "}",
            "",
            "export function appendEnvelopeMeta(",
            "  result: GeneratedRuntimeResult,",
            "  additions: Record<string, unknown>,",
            "): GeneratedRuntimeResult {",
            "  const next = isRecord(result) ? clonePayload(result) as GeneratedRuntimeResult : { data: result };",
            "  const meta = isRecord(next.meta) ? clonePayload(next.meta) : {};",
            "  for (const [key, value] of Object.entries(additions)) {",
            "    if (meta[key] === undefined) {",
            "      meta[key] = value;",
            "    }",
            "  }",
            "  next.meta = meta;",
            "  return next;",
            "}",
            "",
        ]
    )


def render_envelope_module() -> str:
    return "\n".join(
        [
            "export interface ApiEnvelope<TData> {",
            "  trace_id: string;",
            "  request_id?: string;",
            "  data: TData;",
            "  meta?: Record<string, unknown>;",
            "}",
            "",
            "export function buildEnvelope<TData>(",
            "  data: TData,",
            "  ids: { traceId: string; requestId: string },",
            "  meta?: Record<string, unknown>,",
            "): ApiEnvelope<TData> {",
            "  return {",
            "    trace_id: ids.traceId,",
            "    request_id: ids.requestId,",
            "    data,",
            "    meta,",
            "  };",
            "}",
            "",
        ]
    )


def render_errors_module() -> str:
    return "\n".join(
        [
            "export interface ApiErrorEnvelope {",
            "  error_kind: string;",
            "  error_code: string;",
            "  retryability?: string;",
            "  message?: string;",
            "  meta?: Record<string, unknown>;",
            "}",
            "",
            "export class ApiError extends Error {",
            "  readonly status: number;",
            "  readonly envelope: ApiErrorEnvelope;",
            "",
            "  constructor(status: number, envelope: ApiErrorEnvelope) {",
            "    super(`${status} ${envelope.error_code}`);",
            "    this.name = 'ApiError';",
            "    this.status = status;",
            "    this.envelope = envelope;",
            "  }",
            "}",
            "",
            "export function createApiError(",
            "  status: number,",
            "  errorKind: string,",
            "  errorCode: string,",
            "  retryability = 'never',",
            "  message = '',",
            "  meta?: Record<string, unknown>,",
            "): ApiError {",
            "  return new ApiError(status, {",
            "    error_kind: errorKind,",
            "    error_code: errorCode,",
            "    retryability,",
            "    message: message || undefined,",
            "    meta,",
            "  });",
            "}",
            "",
        ]
    )


def render_pagination_module() -> str:
    return "\n".join(
        [
            "export interface CursorPageRequest {",
            "  cursor?: string;",
            "  limit?: number;",
            "}",
            "",
            "export function buildCursorMeta(",
            "  items: unknown[],",
            "  exampleMeta?: Record<string, unknown>,",
            "  nextCursor?: string,",
            "): Record<string, unknown> {",
            "  const meta: Record<string, unknown> = { ...(exampleMeta ?? {}) };",
            "  const resolvedCursor = nextCursor ?? null;",
            "  if (meta.nextCursor === undefined && meta.next_cursor === undefined) {",
            "    meta.nextCursor = resolvedCursor;",
            "    meta.next_cursor = resolvedCursor;",
            "  } else {",
            "    if (meta.nextCursor === undefined) {",
            "      meta.nextCursor = meta.next_cursor ?? resolvedCursor;",
            "    }",
            "    if (meta.next_cursor === undefined) {",
            "      meta.next_cursor = meta.nextCursor ?? resolvedCursor;",
            "    }",
            "  }",
            "  if (meta.returnedCount === undefined && meta.returned_count === undefined) {",
            "    meta.returnedCount = items.length;",
            "    meta.returned_count = items.length;",
            "  } else {",
            "    if (meta.returnedCount === undefined) {",
            "      meta.returnedCount = meta.returned_count ?? items.length;",
            "    }",
            "    if (meta.returned_count === undefined) {",
            "      meta.returned_count = meta.returnedCount ?? items.length;",
            "    }",
            "  }",
            "  return meta;",
            "}",
            "",
        ]
    )


def render_auth_session_module() -> str:
    return "\n".join(
        [
            'import jwt from "jsonwebtoken";',
            'import { createApiError } from "./errors.js";',
            "",
            "export interface AuthSessionContext {",
            "  subject_id: string;",
            "  tenant_id: string;",
            "  roles: string[];",
            "  session_id: string;",
            "  oidc_claims: Record<string, unknown>;",
            "}",
            "",
            "export const ACCESS_TOKEN_TTL_SECONDS = 15 * 60;",
            "export const REFRESH_TOKEN_TTL_SECONDS = 8 * 60 * 60;",
            "",
            "function isRecord(value: unknown): value is Record<string, unknown> {",
            "  return typeof value === 'object' && value !== null && !Array.isArray(value);",
            "}",
            "",
            "function authTokenSecret(): string {",
            '  return process.env.AUTH_TOKEN_SECRET || "phase3-local-dev-secret";',
            "}",
            "",
            "function roleList(value: unknown): string[] {",
            "  if (Array.isArray(value)) {",
            "    return value.filter((item): item is string => typeof item === 'string' && item.length > 0);",
            "  }",
            "  if (typeof value === 'string' && value.trim()) {",
            "    return [value.trim()];",
            "  }",
            "  return [];",
            "}",
            "",
            "function refreshTokenFamilyId(raw: Record<string, unknown>): string {",
            "  const existing = raw.refresh_token_family_id ?? raw.refreshTokenFamilyId;",
            "  if (typeof existing === 'string' && existing.trim()) {",
            "    return existing.trim();",
            "  }",
            "  const sessionId = raw.session_id ?? raw.sid;",
            "  if (typeof sessionId === 'string' && sessionId.trim()) {",
            "    return `refresh-family-${sessionId.trim()}`;",
            "  }",
            "  return 'refresh-family-local';",
            "}",
            "",
            "function rotationCounter(raw: Record<string, unknown>): number {",
            "  const value = raw.rotation_counter ?? raw.rotationCounter;",
            "  return typeof value === 'number' && Number.isFinite(value) ? value : 0;",
            "}",
            "",
            "function signableClaims(raw: Record<string, unknown>): Record<string, unknown> {",
            "  const claims = { ...raw };",
            "  delete claims.exp;",
            "  delete claims.iat;",
            "  delete claims.nbf;",
            "  return claims;",
            "}",
            "",
            "export function issueAuthToken(raw: Record<string, unknown>): string {",
            "  return jwt.sign({ ...signableClaims(raw), token_use: 'access' }, authTokenSecret(), { algorithm: 'HS256', expiresIn: ACCESS_TOKEN_TTL_SECONDS });",
            "}",
            "",
            "export function issueRefreshToken(raw: Record<string, unknown>): string {",
            "  return jwt.sign(",
            "    {",
            "      ...signableClaims(raw),",
            "      token_use: 'refresh',",
            "      refresh_token_family_id: refreshTokenFamilyId(raw),",
            "      rotation_counter: rotationCounter(raw),",
            "    },",
            "    authTokenSecret(),",
            "    { algorithm: 'HS256', expiresIn: REFRESH_TOKEN_TTL_SECONDS },",
            "  );",
            "}",
            "",
            "export function rotateRefreshToken(raw: Record<string, unknown>): string {",
            "  return issueRefreshToken({",
            "    ...raw,",
            "    refresh_token_family_id: refreshTokenFamilyId(raw),",
            "    rotation_counter: rotationCounter(raw) + 1,",
            "  });",
            "}",
            "",
            "export function parseAuthorizationHeader(headerValue: string | undefined): Record<string, unknown> {",
            "  if (!headerValue || !headerValue.trim()) {",
            "    throw createApiError(401, 'auth_error', 'missing_bearer_token', 'caller_after_fix', 'Authorization header must use Bearer token');",
            "  }",
            "  const bearerPrefix = 'Bearer ';",
            "  const token = headerValue.startsWith(bearerPrefix) ? headerValue.slice(bearerPrefix.length).trim() : '';",
            "  if (!token) {",
            "    throw createApiError(401, 'auth_error', 'missing_bearer_token', 'caller_after_fix', 'Authorization header must use Bearer token');",
            "  }",
            "  try {",
            "    const verified = jwt.verify(token, authTokenSecret()) as unknown;",
            "    return isRecord(verified) ? verified : {};",
            "  } catch (error) {",
            "    throw createApiError(",
            "      401,",
            "      'auth_error',",
            "      'invalid_auth_token',",
            "      'caller_after_fix',",
            "      error instanceof Error ? error.message : 'token verification failed',",
            "    );",
            "  }",
            "}",
            "",
            "export function normalizeAuthSession(raw: unknown, fallbackTenantId: string): AuthSessionContext {",
            "  const source = raw && typeof raw === 'object' ? (raw as Record<string, unknown>) : {};",
            "  const tenantId = typeof source.tenant_id === 'string' && source.tenant_id",
            "    ? source.tenant_id",
            "    : (typeof source.tenantId === 'string' && source.tenantId ? source.tenantId : fallbackTenantId);",
            "  const subjectId = typeof source.subject_id === 'string' && source.subject_id",
            "    ? source.subject_id",
            "    : (typeof source.sub === 'string' && source.sub ? source.sub : '');",
            "  const sessionId = typeof source.session_id === 'string' && source.session_id",
            "    ? source.session_id",
            "    : (typeof source.sid === 'string' && source.sid ? source.sid : '');",
            "  const roles = roleList(source.roles).length > 0 ? roleList(source.roles) : roleList(source.role);",
            "  const oidcClaims = isRecord(source.oidc_claims)",
            "    ? (source.oidc_claims as Record<string, unknown>)",
            "    : source;",
            "  if (!tenantId || !subjectId || !sessionId || roles.length === 0) {",
            "    throw createApiError(401, 'auth_error', 'invalid_auth_context', 'caller_after_fix', 'tenant/session claims are missing');",
            "  }",
            "  return {",
            "    subject_id: subjectId,",
            "    tenant_id: tenantId,",
            "    roles,",
            "    session_id: sessionId,",
            "    oidc_claims: oidcClaims,",
            "  };",
            "}",
            "",
            "export function requireRbacRole(session: AuthSessionContext, role: string): void {",
            "  if (!session.roles.includes(role)) {",
            "    throw createApiError(403, 'business_error', 'rbac_forbidden', 'never', `Missing role: ${role}`);",
            "  }",
            "}",
            "",
        ]
    )


def index_compiled_bindings_by_endpoint(
    compiled_bindings: list[dict[str, Any]] | None,
) -> dict[tuple[str, str], list[dict[str, Any]]]:
    binding_index: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for row in compiled_bindings or []:
        method = str(row.get("http_method") or "").strip().upper()
        path = str(row.get("api_endpoint") or "").strip()
        if not method or not path:
            continue
        binding_index.setdefault((method, path), []).append(row)
    return binding_index


def binding_rbac_policies(rows: list[dict[str, Any]], *, locale: str | None = None) -> list[str]:
    return ordered_ui_roles(
        *[
            extract_ui_policy_roles(
                row.get("rbac_policy") or row.get("visibility_rule") or "",
                locale=locale,
            )
            for row in rows
            if isinstance(row, dict)
        ],
        locale=locale,
    )


def render_generated_runtime_facade() -> str:
    return "\n".join(
        [
            'import {',
            "  buildFailurePayload,",
            "  buildOperationPayload,",
            "  countGeneratedRecords,",
            "  getAuditRecords,",
            "  getGeneratedRecord,",
            "  invokeGeneratedOperation as invokeOperationSupport,",
            "  listGeneratedRecords,",
            "  normalizeIdValue,",
            "  persistenceProbeHints,",
            "  recordGeneratedAuditEvent,",
            "  resetGeneratedRuntime as resetSupportRuntime,",
            "  seedGeneratedRuntimePersistence as seedSupportPersistence,",
            "  seedGeneratedRuntimeState as seedSupportRuntimeState,",
            '} from "./operation-support.js";',
            "",
            "/**",
            " * Compatibility facade kept for existing tests and bootstrap tooling.",
            " *",
            " * Real repository execution should import explicit helpers from",
            " * `operation-support.ts` instead of routing every call through this facade.",
            " */",
            "",
            "export {",
            "  buildFailurePayload,",
            "  buildOperationPayload,",
            "  countGeneratedRecords,",
            "  getAuditRecords,",
            "  getGeneratedRecord,",
            "  listGeneratedRecords,",
            "  normalizeIdValue,",
            "  persistenceProbeHints,",
            "  recordGeneratedAuditEvent,",
            "  seedSupportPersistence as seedGeneratedRuntimePersistence,",
            "  seedSupportRuntimeState as seedGeneratedRuntimeState,",
            "};",
            "",
            "export function resetGeneratedRuntime(): void {",
            "  resetSupportRuntime();",
            "}",
            "",
            "export async function invokeGeneratedOperation(operationId: string, payload: unknown): Promise<unknown> {",
            "  return invokeOperationSupport(operationId, payload);",
            "}",
            "",
        ]
    )


def render_runtime_test_kit(
    *,
    operations_by_tag: dict[str, list[dict[str, str]]],
) -> str:
    import_lines = [
        'import { ApiError } from "../../apps/api/src/common/errors";',
        'import {',
        "  buildFailurePayload,",
        "  buildOperationPayload,",
        "  countGeneratedRecords,",
        "  getGeneratedRecord,",
        "  getAuditRecords,",
        "  invokeGeneratedOperation,",
        "  listGeneratedRecords,",
        "  resetGeneratedRuntime as resetGeneratedRuntimeSupport,",
        '} from "../../apps/api/src/common/generated-runtime";',
    ]
    handler_lines = [
        "const operationHandlers: Record<string, (payload: unknown) => Promise<unknown>> = {",
    ]
    for module_slug, grouped_operations in operations_by_tag.items():
        controller_class = f"{camel_case(module_slug)}Controller"
        import_lines.append(
            f'import {{ {controller_class} }} from "../../apps/api/src/modules/{module_slug}/{module_slug}.controller";'
        )
        for operation in grouped_operations:
            operation_id = operation["operation_id"] or f"{operation['method']}-{operation['path']}"
            method_name = lower_camel(operation_id)
            handler_lines.append(
                f'  "{operation_id}": (payload) => new {controller_class}().{method_name}(payload),'
            )
    handler_lines.extend(["};", ""])
    body = [
        "",
        *handler_lines,
        "type RuntimeContext = Record<string, unknown>;",
        "",
        "function deepClone<T>(value: T): T {",
        "  if (value === undefined) {",
        "    return value;",
        "  }",
        "  return JSON.parse(JSON.stringify(value)) as T;",
        "}",
        "",
        "function isRecord(value: unknown): value is Record<string, unknown> {",
        "  return typeof value === \"object\" && value !== null && !Array.isArray(value);",
        "}",
        "",
        "function snakeCase(value: string): string {",
        "  return value.replace(/([a-z0-9])([A-Z])/g, \"$1_$2\").toLowerCase();",
        "}",
        "",
        "function isTrackedContextField(key: string): boolean {",
        "  return key.endsWith(\"_id\") || key.endsWith(\"Id\") || key === \"state\" || key === \"status\" || key === \"row_version\" || key === \"version\" || key.endsWith(\"_version\") || key.endsWith(\"Version\") || key === \"uncertainty_level\" || key === \"uncertaintyLevel\";",
        "}",
        "",
        "function stripIdSuffix(value: string): string {",
        "  if (value.endsWith(\"_id\")) {",
        "    return value.slice(0, -3);",
        "  }",
        "  if (value.endsWith(\"Id\")) {",
        "    return value.slice(0, -2);",
        "  }",
        "  return value;",
        "}",
        "",
        "function tokenParts(value: string): string[] {",
        "  return value.split(\"_\").filter(Boolean);",
        "}",
        "",
        "function scoreContextKey(requestedKey: string, candidateKey: string): number {",
        "  if (candidateKey === requestedKey) {",
        "    return 100;",
        "  }",
        "  const requestedCore = stripIdSuffix(requestedKey);",
        "  const candidateCore = stripIdSuffix(candidateKey);",
        "  if (candidateCore === requestedCore) {",
        "    return 90;",
        "  }",
        "  if (candidateCore.endsWith(requestedCore) || requestedCore.endsWith(candidateCore)) {",
        "    return 80;",
        "  }",
        "  const requestedTokens = tokenParts(requestedCore);",
        "  const candidateTokens = tokenParts(candidateCore);",
        "  const overlap = requestedTokens.filter((token) => candidateTokens.includes(token)).length;",
        "  return overlap > 0 ? overlap * 10 : -1;",
        "}",
        "",
        "function resolveContextKey(key: string, context: RuntimeContext): string {",
        "  const requested = snakeCase(key);",
        "  let bestKey = \"\";",
        "  let bestScore = -1;",
        "  for (const candidate of Object.keys(context)) {",
        "    const score = scoreContextKey(requested, snakeCase(candidate));",
        "    if (score > bestScore) {",
        "      bestKey = candidate;",
        "      bestScore = score;",
        "    }",
        "  }",
        "  return bestKey;",
        "}",
        "",
        "function hasMeaningfulValue(value: unknown): boolean {",
        "  if (value === undefined || value === null) {",
        "    return false;",
        "  }",
        "  if (typeof value === \"string\") {",
        "    return value.trim().length > 0;",
        "  }",
        "  return true;",
        "}",
        "",
        "function shouldPreserveExplicitField(key: string, value: unknown): boolean {",
        "  const normalized = snakeCase(key);",
        "  return hasMeaningfulValue(value) && (normalized === \"status\" || normalized === \"state\" || normalized.endsWith(\"_id\") || normalized === \"version\" || normalized === \"expected_version\");",
        "}",
        "",
        "function withPersistenceDisabled<T>(run: () => T): T {",
        "  const databaseUrl = process.env.DATABASE_URL;",
        "  const postgresHostPort = process.env.POSTGRES_HOST_PORT;",
        "  delete process.env.DATABASE_URL;",
        "  delete process.env.POSTGRES_HOST_PORT;",
        "  try {",
        "    return run();",
        "  } finally {",
        "    if (databaseUrl === undefined) {",
        "      delete process.env.DATABASE_URL;",
        "    } else {",
        "      process.env.DATABASE_URL = databaseUrl;",
        "    }",
        "    if (postgresHostPort === undefined) {",
        "      delete process.env.POSTGRES_HOST_PORT;",
        "    } else {",
        "      process.env.POSTGRES_HOST_PORT = postgresHostPort;",
        "    }",
        "  }",
        "}",
        "",
        "async function withPersistenceDisabledAsync<T>(run: () => Promise<T>): Promise<T> {",
        "  const databaseUrl = process.env.DATABASE_URL;",
        "  const postgresHostPort = process.env.POSTGRES_HOST_PORT;",
        "  delete process.env.DATABASE_URL;",
        "  delete process.env.POSTGRES_HOST_PORT;",
        "  try {",
        "    return await run();",
        "  } finally {",
        "    if (databaseUrl === undefined) {",
        "      delete process.env.DATABASE_URL;",
        "    } else {",
        "      process.env.DATABASE_URL = databaseUrl;",
        "    }",
        "    if (postgresHostPort === undefined) {",
        "      delete process.env.POSTGRES_HOST_PORT;",
        "    } else {",
        "      process.env.POSTGRES_HOST_PORT = postgresHostPort;",
        "    }",
        "  }",
        "}",
        "",
        "export {",
        "  buildFailurePayload,",
        "  buildOperationPayload,",
        "  countGeneratedRecords,",
        "  getAuditRecords,",
        "};",
        "",
        "export function resetGeneratedRuntime(): void {",
        "  withPersistenceDisabled(() => {",
        "    resetGeneratedRuntimeSupport();",
        "  });",
        "}",
        "",
        "",
        "export async function invokeOperation(operationId: string, payload: unknown): Promise<unknown> {",
        "  return withPersistenceDisabledAsync(async () => {",
        "    const handler = operationHandlers[operationId];",
        "    if (handler) {",
        "      return handler(payload);",
        "    }",
        "    return invokeGeneratedOperation(operationId, payload);",
        "  });",
        "}",
        "",
        "export function extractEnvelopeData<T = unknown>(result: unknown): T {",
        "  if (!isRecord(result) || !(\"data\" in result)) {",
        '    throw new Error("Expected envelope with data");',
        "  }",
        "  return result.data as T;",
        "}",
        "",
        "export function applyRuntimeContext(payload: unknown, context: RuntimeContext): Record<string, unknown> {",
        "  const next = isRecord(payload) ? deepClone(payload) : {};",
        "  for (const key of Object.keys(next)) {",
        "    if (key === \"path_params\" || key === \"auth_context\") {",
        "      continue;",
        "    }",
        "    if (!isTrackedContextField(key)) {",
        "      continue;",
        "    }",
        "    if (shouldPreserveExplicitField(key, next[key])) {",
        "      continue;",
        "    }",
        "    const match = resolveContextKey(key, context);",
        "    if (match) {",
        "      next[key] = context[match];",
        "    }",
        "  }",
        "  if (isRecord(next.path_params)) {",
        "    const pathParams = next.path_params;",
        "    for (const key of Object.keys(pathParams)) {",
        "      if (!isTrackedContextField(key)) {",
        "        continue;",
        "      }",
        "      const match = resolveContextKey(key, context);",
        "      if (match) {",
        "        pathParams[key] = context[match];",
        "      }",
        "    }",
        "    next.path_params = pathParams;",
        "  }",
        "  if (isRecord(next.auth_context)) {",
        "    const authContext = next.auth_context;",
        "    const tenantMatch = resolveContextKey(\"tenant_id\", context);",
        "    if (tenantMatch) {",
        "      authContext.tenant_id = context[tenantMatch];",
        "    }",
        "    next.auth_context = authContext;",
        "  }",
        "  return next;",
        "}",
        "",
        "export function absorbEnvelopeContext(result: unknown, context: RuntimeContext): RuntimeContext {",
        "  const data = extractEnvelopeData<unknown>(result);",
        "  const source = Array.isArray(data) ? data.find((item) => isRecord(item)) : data;",
        "  if (!isRecord(source)) {",
        "    return context;",
        "  }",
        "  for (const [key, value] of Object.entries(source)) {",
        "    if (isTrackedContextField(key)) {",
        "      context[key] = value;",
        "    }",
        "  }",
        "  return context;",
        "}",
        "",
        "export function getRecord(recordKey: string, id: string): Record<string, unknown> | undefined {",
        "  return getGeneratedRecord(recordKey, id);",
        "}",
        "",
        "export function listRecords(recordKey: string): Record<string, unknown>[] {",
        "  return listGeneratedRecords(recordKey);",
        "}",
        "",
        "export function latestAuditRecord(): Record<string, unknown> | undefined {",
        "  const records = getAuditRecords();",
        "  return records.length > 0 ? (records.at(-1) as Record<string, unknown>) : undefined;",
        "}",
        "",
        "export async function captureApiError(action: Promise<unknown>): Promise<ApiError> {",
        "  try {",
        "    await action;",
        "  } catch (error) {",
        "    if (error instanceof ApiError) {",
        "      return error;",
        "    }",
        "    throw error;",
        "  }",
        '  throw new Error("Expected ApiError");',
        "}",
        "",
    ]
    return "\n".join(import_lines + body)


def render_generated_api_router(
    *,
    operations_by_tag: dict[str, list[dict[str, str]]],
    operation_specs: dict[str, dict[str, Any]],
    compiled_bindings: list[dict[str, Any]] | None = None,
) -> str:
    import_lines = [
        'import type { IncomingMessage, ServerResponse } from "node:http";',
        'import { URL } from "node:url";',
        'import { normalizeAuthSession, parseAuthorizationHeader } from "./common/auth-session.js";',
        'import { ApiError, createApiError } from "./common/errors.js";',
        'import { recordGeneratedAuditEvent } from "./common/operation-support.js";',
    ]
    binding_index = index_compiled_bindings_by_endpoint(compiled_bindings)
    route_rows: list[str] = []
    for module_slug, grouped_operations in operations_by_tag.items():
        controller_class = f"{camel_case(module_slug)}Controller"
        import_lines.append(f'import {{ {controller_class} }} from "./modules/{module_slug}/{module_slug}.controller.js";')
        for operation in grouped_operations:
            operation_id = operation["operation_id"] or f"{operation['method']}-{operation['path']}"
            spec = runtime_spec_for_operation(operation, operation_specs)
            success_status = int(str(spec.get("successStatus", "200")).strip() or "200")
            matching_bindings = binding_index.get((str(operation["method"]).upper(), str(operation["path"]).strip()), [])
            binding_sources = [
                str(row.get("service_binding_id") or "").strip()
                for row in matching_bindings
                if str(row.get("service_binding_id") or "").strip()
            ]
            binding_modes = sorted(
                {
                    str(row.get("binding_mode") or "").strip()
                    for row in matching_bindings
                    if str(row.get("binding_mode") or "").strip()
                }
            )
            rbac_policies = binding_rbac_policies(matching_bindings)
            failure_semantics = sorted(
                {
                    str(row.get("failure_codes") or "").strip()
                    for row in matching_bindings
                    if str(row.get("failure_codes") or "").strip()
                }
            )
            route_rows.extend(
                [
                    "  {",
                    f'    operationId: "{operation_id}",',
                    f'    method: "{str(operation["method"]).upper()}",',
                    f'    pathTemplate: "{operation["path"]}",',
                    f"    successStatus: {success_status},",
                    f"    bindingSources: {json.dumps(binding_sources, ensure_ascii=False)},",
                    f"    bindingModes: {json.dumps(binding_modes, ensure_ascii=False)},",
                    f"    rbacPolicies: {json.dumps(rbac_policies, ensure_ascii=False)},",
                    f"    failureSemantics: {json.dumps(failure_semantics, ensure_ascii=False)},",
                    f"    handler: (payload) => new {controller_class}().{lower_camel(operation_id)}(payload),",
                    "  },",
                ]
            )
    return "\n".join(
        import_lines
        + [
            "",
            f'// Derived artifact authority: {"compiled-bindings" if binding_index else "missing-compiled-bindings"}',
            "type RouteDef = {",
            "  operationId: string;",
            "  method: string;",
            "  pathTemplate: string;",
            "  successStatus: number;",
            "  bindingSources: string[];",
            "  bindingModes: string[];",
            "  rbacPolicies: string[];",
            "  failureSemantics: string[];",
            "  handler: (payload: Record<string, unknown>) => Promise<unknown>;",
            "};",
            "",
            "const routeTable: RouteDef[] = [",
            *route_rows,
            "];",
            "",
            "function isRecord(value: unknown): value is Record<string, unknown> {",
            "  return typeof value === \"object\" && value !== null && !Array.isArray(value);",
            "}",
            "",
            "async function readJsonBody(request: IncomingMessage): Promise<Record<string, unknown>> {",
            "  const chunks: Buffer[] = [];",
            "  for await (const chunk of request) {",
            "    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));",
            "  }",
            "  if (chunks.length === 0) {",
            "    return {};",
            "  }",
            "  const raw = Buffer.concat(chunks).toString(\"utf-8\").trim();",
            "  if (!raw) {",
            "    return {};",
            "  }",
            "  const parsed = JSON.parse(raw) as unknown;",
            "  return isRecord(parsed) ? parsed : {};",
            "}",
            "",
            "function buildQuery(url: URL): Record<string, unknown> {",
            "  const entries = Array.from(url.searchParams.entries());",
            "  return Object.fromEntries(entries);",
            "}",
            "",
            "function matchPath(pathTemplate: string, actualPath: string): Record<string, string> | null {",
            "  const templateParts = pathTemplate.split(\"/\").filter(Boolean);",
            "  const actualParts = actualPath.split(\"/\").filter(Boolean);",
            "  if (templateParts.length !== actualParts.length) {",
            "    return null;",
            "  }",
            "  const params: Record<string, string> = {};",
            "  for (let index = 0; index < templateParts.length; index += 1) {",
            "    const templatePart = templateParts[index];",
            "    const actualPart = decodeURIComponent(actualParts[index] ?? \"\");",
            "    if (templatePart.startsWith(\"{\") && templatePart.endsWith(\"}\")) {",
            "      params[templatePart.slice(1, -1)] = actualPart;",
            "      continue;",
            "    }",
            "    if (templatePart !== actualPart) {",
            "      return null;",
            "    }",
            "  }",
            "  return params;",
            "}",
            "",
            "function allowPhase3AuthContextHeader(): boolean {",
            "  return process.env.PHASE3_ALLOW_AUTH_CONTEXT_HEADER === \"true\";",
            "}",
            "",
            "function parsePhase3AuthContextHeader(request: IncomingMessage): Record<string, unknown> {",
            "  if (!allowPhase3AuthContextHeader()) {",
            "    return {};",
            "  }",
            "  const raw = request.headers[\"x-phase3-auth-context\"];",
            "  const value = Array.isArray(raw) ? raw[0] : raw;",
            "  if (typeof value !== \"string\" || !value.trim()) {",
            "    return {};",
            "  }",
            "  try {",
            "    const parsed = JSON.parse(decodeURIComponent(value)) as unknown;",
            "    return isRecord(parsed) ? parsed : {};",
            "  } catch {",
            "    return {};",
            "  }",
            "}",
            "",
            "function parseAuthContext(request: IncomingMessage): Record<string, unknown> {",
            "  const raw = request.headers.authorization;",
            "  const authorization = Array.isArray(raw) ? raw[0] : raw;",
            "  if (typeof authorization === \"string\" && authorization.trim()) {",
            "    return parseAuthorizationHeader(authorization);",
            "  }",
            "  const fallbackContext = parsePhase3AuthContextHeader(request);",
            "  if (Object.keys(fallbackContext).length > 0) {",
            "    return fallbackContext;",
            "  }",
            "  return parseAuthorizationHeader(undefined);",
            "}",
            "",
            "function stringValue(value: unknown): string {",
            "  return typeof value === \"string\" ? value.trim() : \"\";",
            "}",
            "",
            "function uniqueNonEmpty(values: string[]): string[] {",
            "  return Array.from(new Set(values.map((value) => String(value).trim()).filter(Boolean)));",
            "}",
            "",
            "function deriveRouteTenantId(",
            "  authContext: Record<string, unknown>,",
            "  payload: Record<string, unknown>,",
            "  pathParams: Record<string, string>,",
            "): string {",
            "  const body = isRecord(payload.body) ? payload.body : {};",
            "  return stringValue(payload.tenant_id)",
            "    || stringValue(payload.tenantId)",
            "    || stringValue(body.tenant_id)",
            "    || stringValue(body.tenantId)",
            "    || stringValue(pathParams.tenant_id)",
            "    || stringValue(pathParams.tenantId)",
            "    || stringValue(authContext.tenant_id)",
            "    || stringValue(authContext.tenantId);",
            "}",
            "",
            "function applyRouteTenantContext(",
            "  payload: Record<string, unknown>,",
            "  pathParams: Record<string, string>,",
            "  authContext: Record<string, unknown>,",
            "  tenantId: string,",
            "): void {",
            "  if (!tenantId) {",
            "    return;",
            "  }",
            "  if (payload.tenant_id === undefined && payload.tenantId === undefined) {",
            "    payload.tenant_id = tenantId;",
            "  }",
            "  const body = isRecord(payload.body) ? payload.body : undefined;",
            "  if (body && body.tenant_id === undefined && body.tenantId === undefined) {",
            "    body.tenant_id = tenantId;",
            "  }",
            "  if (",
            "    (Object.prototype.hasOwnProperty.call(pathParams, \"tenant_id\") || Object.prototype.hasOwnProperty.call(pathParams, \"tenantId\"))",
            "    && pathParams.tenant_id === undefined",
            "    && pathParams.tenantId === undefined",
            "  ) {",
            "    pathParams.tenant_id = tenantId;",
            "  }",
            "  if (authContext.tenant_id === undefined && authContext.tenantId === undefined) {",
            "    authContext.tenant_id = tenantId;",
            "  }",
            "}",
            "",
            "function enforceRouteRbacPolicies(",
            "  route: RouteDef,",
            "  authContext: Record<string, unknown>,",
            "  payload: Record<string, unknown>,",
            "  pathParams: Record<string, string>,",
            "): string {",
            "  const tenantId = deriveRouteTenantId(authContext, payload, pathParams);",
            "  const requiredRoles = uniqueNonEmpty(route.rbacPolicies || []);",
            "  const effectiveRoles = requiredRoles.length > 0 ? requiredRoles : [\"authenticated\"];",
            "  const session = normalizeAuthSession(authContext, tenantId || \"11111111-1111-1111-1111-111111111111\");",
            "  if (!effectiveRoles.some((role) => session.roles.includes(role))) {",
            "    throw createApiError(403, \"business_error\", \"rbac_forbidden\", \"never\", `Missing one of roles: ${effectiveRoles.join(\", \")}`);",
            "  }",
            "  return stringValue(session.tenant_id) || tenantId;",
            "}",
            "",
            "function auditRouteDenial(",
            "  route: RouteDef,",
            "  error: ApiError,",
            "  authContext: Record<string, unknown>,",
            "  payload: Record<string, unknown>,",
            "  pathParams: Record<string, string>,",
            "): void {",
            "  recordGeneratedAuditEvent({",
            "    tenantId: deriveRouteTenantId(authContext, payload, pathParams) || stringValue(authContext.tenant_id) || stringValue(authContext.tenantId),",
            "    operationId: route.operationId,",
            "    actionType: route.operationId,",
            "    outcome: \"denied\",",
            "    reason: error.envelope.error_code,",
            "    subjectId: stringValue(authContext.subject_id) || stringValue(authContext.sub),",
            "    requestId: stringValue(payload.request_id) || stringValue(payload.requestId),",
            "  });",
            "}",
            "",
            "function failureCodeFromHeader(request: IncomingMessage): string {",
            "  const raw = request.headers[\"x-phase3-force-error-code\"];",
            "  const value = Array.isArray(raw) ? raw[0] : raw;",
            "  return typeof value === \"string\" ? value : \"\";",
            "}",
            "",
            "export async function handleGeneratedApiRequest(",
            "  request: IncomingMessage,",
            "  response: ServerResponse,",
            "  helpers: { sendJson: (response: ServerResponse, statusCode: number, payload: Record<string, unknown>) => void },",
            "): Promise<boolean> {",
            "  const method = request.method || \"GET\";",
            "  const url = new URL(request.url || \"/\", `http://${request.headers.host || \"localhost\"}`);",
            "  for (const route of routeTable) {",
            "    if (route.method !== method) {",
            "      continue;",
            "    }",
            "    const pathParams = matchPath(route.pathTemplate, url.pathname);",
            "    if (!pathParams) {",
            "      continue;",
            "    }",
            "    let authContext: Record<string, unknown> = {};",
            "    let payload: Record<string, unknown> = {};",
            "    try {",
            "      const body = await readJsonBody(request);",
            "      const query = buildQuery(url);",
            "      authContext = parseAuthContext(request);",
            "      const forceErrorCode = failureCodeFromHeader(request);",
            "      payload = {",
            "        ...query,",
            "        ...body,",
            "        body,",
            "        query,",
            "        path_params: pathParams,",
            "        pathParams: pathParams,",
            "        auth_context: authContext,",
            "        authContext: authContext,",
            "      };",
            "      const tenantId = enforceRouteRbacPolicies(route, authContext, payload, pathParams);",
            "      applyRouteTenantContext(payload, pathParams, authContext, tenantId);",
            "      if (forceErrorCode) {",
            "        payload.force_error_code = forceErrorCode;",
            "      }",
            "      const result = await route.handler(payload);",
            "      helpers.sendJson(response, route.successStatus, isRecord(result) ? result : { data: result });",
            "    } catch (error) {",
            "      if (error instanceof ApiError) {",
            "        auditRouteDenial(route, error, authContext, payload, pathParams);",
            "        helpers.sendJson(response, error.status, error.envelope as unknown as Record<string, unknown>);",
            "      } else {",
            "        helpers.sendJson(response, 500, {",
            '          error_kind: "system_error",',
            '          error_code: "generated_route_handler_failed",',
            "          message: error instanceof Error ? error.message : String(error),",
            "        });",
            "      }",
            "    }",
            "    return true;",
            "  }",
            "  return false;",
            "}",
            "",
        ]
    )


def render_generated_runtime_positioning() -> str:
    return "\n".join(
        [
            "# Generated Runtime Positioning",
            "",
            "## Scope",
            "- The foundation package may include a generated runtime to bootstrap early verification, but Phase-3 is not complete while business behavior still depends primarily on it.",
            "- `generated-runtime.ts` now exists as a compatibility facade; shared execution semantics live in `operation-support.ts`, and repository modules should bind through explicit operation plans rather than treating the facade as the default backend.",
            "- Generated controller/service/repository adapters preserve the frozen Phase-2 contract surface, but they must be replaced with real implementation code before `delivery-ready`.",
            "",
            "## Why This Exists In Phase-3",
            "- It makes contract, scenario, replay, lint, typecheck, and build lanes executable early in the implementation cycle.",
            "- It exposes semantic gaps early without claiming that the underlying business/domain stack is complete.",
            "",
            "## Concurrency Validation Boundary",
            "- Phase-3 conflict scenarios normally validate deterministic conflict-path semantics against the generated runtime.",
            "- They prove idempotency, version-conflict handling, retry guidance, and authoritative final state preservation.",
            "- They do not, by themselves, prove production-grade parallel race safety, database lock behavior, or multi-node contention correctness.",
            "",
            "## Replacement Rule",
            "1. Replace repository delegates with real DAL/domain implementations during Phase-3 implementation, not as a default deferred step.",
            "2. Keep the frozen OpenAPI plus unit/contract/scenario/replay tests green during each replacement.",
            "3. Do not treat `generated-runtime.ts` as delivery evidence once real implementation work is underway.",
            "",
            "## Completion Interpretation",
            "- `foundation-ready` means the scaffold and failing-test package are frozen and implementation may start.",
            "- `delivery-ready` requires runnable implementation code plus executed unit/contract/scenario/replay evidence; scaffold-only runtime behavior is insufficient.",
            "",
        ]
    )
