#!/usr/bin/env python3
"""
Generate a typed API client skeleton from a JSON-compatible OpenAPI document.
"""

from __future__ import annotations

from pathlib import Path
import sys

SCRIPTS_ROOT = Path(__file__).resolve().parents[1]
if str(SCRIPTS_ROOT) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_ROOT))


import argparse
import json
from pathlib import Path

from phase3.openapi_to_types import iter_operation_models
from phase3.contract_tools import load_openapi_document


def client_method_name(operation_id: str) -> str:
    return operation_id[:1].lower() + operation_id[1:]


def build_api_client_document(spec: dict[str, object]) -> str:
    lines = [
        "// Generated by api_client_scaffolder.py",
        f'// Derived artifact authority: {str(spec.get("x-derived-authority", "openapi")).strip() or "openapi"}',
        'import type * as SharedTypes from "../shared-types";',
        "",
        "export interface ApiClientTransport {",
        "  request<TResponse>(config: {",
        "    method: string;",
        "    path: string;",
        "    query?: Record<string, unknown>;",
        "    body?: unknown;",
        "  }): Promise<TResponse>;",
        "}",
        "",
        "function fillPath(path: string, pathParams?: Record<string, unknown>): string {",
        "  if (!pathParams) return path;",
        "  return path.replace(/\\{([^}]+)\\}/g, (_, key: string) => encodeURIComponent(String(pathParams[key])));",
        "}",
        "",
        "export function createApiClient(transport: ApiClientTransport) {",
        "  return {",
    ]

    for model in iter_operation_models(spec):
        operation_id = str(model["operation_id"])
        method_name = client_method_name(operation_id)
        input_type = f"SharedTypes.{model['input_type_name']}"
        response_type = f"SharedTypes.{model['response_type_name']}"
        has_input = bool(model["has_path"] or model["has_query"] or model["has_body"])
        signature = f"input: {input_type}" if has_input else f"input: {input_type} = {{}}"
        if model["binding_sources"] or model["binding_modes"] or model["rbac_policies"] or model["failure_semantics"]:
            lines.append(
                "    // Derived from compiled bindings: "
                + ", ".join(model["binding_sources"] or ["none"])
            )
            if model["binding_modes"]:
                lines.append("    // Binding modes: " + ", ".join(model["binding_modes"]))
            if model["rbac_policies"]:
                lines.append("    // RBAC policies: " + ", ".join(model["rbac_policies"]))
            if model["failure_semantics"]:
                lines.append("    // Failure semantics: " + " | ".join(model["failure_semantics"]))
        lines.extend(
            [
                f"    async {method_name}({signature}): Promise<{response_type}> {{",
                "      return transport.request({",
                f'        method: "{str(model["method"]).upper()}",',
                f'        path: fillPath("{str(model["path"])}", input.pathParams as Record<string, unknown> | undefined),',
                "        query: input.query as Record<string, unknown> | undefined,",
                "        body: input.body,",
                "      });",
                "    },",
                "",
            ]
        )

    lines.extend(["  };", "}", ""])
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate a typed API client skeleton from OpenAPI")
    parser.add_argument("--openapi", required=True)
    parser.add_argument("--output", required=True)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    spec = load_openapi_document(Path(args.openapi).resolve())
    document = build_api_client_document(spec)
    output_path = Path(args.output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(document, encoding="utf-8")
    print(json.dumps({"output": str(output_path)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
