#!/usr/bin/env python3
"""
Generate the Phase-3 tech-stack decision file from Phase-2 implementation inputs.
"""

from __future__ import annotations

from pathlib import Path
import sys

SCRIPTS_ROOT = Path(__file__).resolve().parents[1]
if str(SCRIPTS_ROOT) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_ROOT))


import argparse
import json
from pathlib import Path

from common.output_language import is_zh_output, resolve_output_locale
from phase3.contract_tools import (
    auth_vendor_contract_source,
    extract_nested_bullet_items,
    parse_auth_vendor_rows,
    parse_technology_selection_rows,
)


def choose_front_runner(rows: list[dict[str, object]], *, status_field: str, default_key: str) -> str:
    for row in rows:
        if str(row.get(status_field, "")).strip().lower() in {"chosen", "provisional-front-runner", "front-runner"}:
            return str(row.get(default_key, "")).strip()
    if rows:
        return str(rows[0].get(default_key, "")).strip()
    return "unknown"


def build_stack_decision_document(
    *,
    esp_text: str,
    stage_03_text: str,
    stage_04_text: str,
    title: str = "Phase-3 Stack Decision",
    output_locale: str | None = None,
) -> str:
    try:
        technology_rows = parse_technology_selection_rows(stage_03_text)
    except ValueError:
        technology_rows = parse_technology_selection_rows(esp_text)
    auth_vendor_rows = parse_auth_vendor_rows(esp_text)
    auth_contract_source = auth_vendor_contract_source(esp_text)
    assumptions = extract_nested_bullet_items(stage_03_text, "technology_stack_and_deployment_assumptions")
    if not assumptions:
        assumptions = extract_nested_bullet_items(esp_text, "technology_stack_and_deployment_assumptions")
    recommended_auth = extract_nested_bullet_items(esp_text, "recommended_approach")
    primary_surfaces = extract_nested_bullet_items(esp_text, "primary_surfaces")

    chosen_candidate = choose_front_runner(technology_rows, status_field="final_decision", default_key="candidate_name")
    preferred_auth_vendor = choose_front_runner(
        auth_vendor_rows,
        status_field="decision_status",
        default_key="candidate",
    )

    chosen_lower = chosen_candidate.lower()
    assumptions_lower = " ".join(assumptions).lower()
    database = "postgresql" if "postgresql" in chosen_lower or "postgresql" in assumptions_lower else "unknown"
    queue = "redis" if "redis" in chosen_lower or "redis" in assumptions_lower else "none"
    topology = "modular-monolith" if "modular monolith" in chosen_lower else "custom"
    backend_language = "typescript" if "typescript" in assumptions_lower else "unknown"
    backend_framework = "node-http"
    frontend_framework = "react-vite"
    frontend_lane = "ia-contract-mvp"
    api_shape = "bff-api-edge" if "api edge" in assumptions_lower or "bff" in assumptions_lower else "service-api"
    external_auth_frozen = auth_contract_source == "explicit-table"
    identity_posture = (
        recommended_auth[0]
        if recommended_auth and external_auth_frozen
        else "real session or token auth boundary with tenant-scoped role claims"
    )
    auth_integration_mode = "external-idp" if external_auth_frozen else "runtime-agnostic-real-auth"

    zh = is_zh_output(output_locale)
    lines = [
        "# Generated by phase3_stack_decision.py",
        f"title: {json.dumps(title, ensure_ascii=False)}",
        "version: \"0.1\"",
        "selection_source:",
        f"  chosen_candidate: {json.dumps(chosen_candidate, ensure_ascii=False)}",
        f"  preferred_auth_vendor: {json.dumps(preferred_auth_vendor, ensure_ascii=False)}",
        "application_topology:",
        f"  shape: {json.dumps(topology)}",
        f"  api_shape: {json.dumps(api_shape)}",
        "runtime:",
        f"  backend_language: {json.dumps(backend_language)}",
        f"  backend_framework: {json.dumps(backend_framework)}",
        f"  frontend_framework: {json.dumps(frontend_framework)}",
        f"  frontend_lane: {json.dumps(frontend_lane)}",
        "storage:",
        f"  primary_database: {json.dumps(database)}",
        f"  queue_or_coordination_store: {json.dumps(queue)}",
        '  object_or_secret_storage: "managed"',
        "identity:",
        f"  posture: {json.dumps(identity_posture, ensure_ascii=False)}",
        f"  preferred_vendor_class: {json.dumps(preferred_auth_vendor, ensure_ascii=False)}",
        f"  contract_source: {json.dumps(auth_contract_source, ensure_ascii=False)}",
        f"  integration_mode: {json.dumps(auth_integration_mode, ensure_ascii=False)}",
        "delivery_expression:",
        f"  web_surface_count: {len(primary_surfaces)}",
        f"  primary_surface_mode: {json.dumps('完整业务工作流 Web 页面' if zh else 'workflow-complete web surfaces', ensure_ascii=False)}",
        "phase3_defaults:",
        (
            '  frontend_default_source: "Phase-3 v0.1 默认前端来源：因为 P2 没有冻结 Web 框架"'
            if zh
            else '  frontend_default_source: "Phase-3 v0.1 default because P2 does not freeze the web framework"'
        ),
        (
            '  backend_default_source: "Phase-3 v0.1 默认后端来源：因为 P2 没有冻结后端框架，所以采用 Node HTTP + TypeScript 服务通道"'
            if zh
            else '  backend_default_source: "Phase-3 v0.1 default Node HTTP + TypeScript service lane because P2 does not freeze a backend framework"'
        ),
        "assumptions:",
    ]
    for item in assumptions:
        lines.append(f"  - {json.dumps(item, ensure_ascii=False)}")
    if not assumptions:
        lines.append('  - "未提取到显式技术假设"' if zh else '  - "no explicit technology assumptions extracted"')
    lines.append("notes:")
    lines.append(
        '  - "P2 仍然是数据库/队列/认证/拓扑决策的事实来源；P3 负责把这些决策实例化成可运行 scaffold。"'
        if zh
        else '  - "P2 remains the source of truth for DB/queue/auth/topology decisions; P3 instantiates them into a runnable scaffold."'
    )
    lines.append(
        '  - "除非 P2 或 Phase-3 ADR 明确覆盖，否则前端运行时默认采用 React + Vite MVP 通道。"'
        if zh
        else '  - "Frontend runtime defaults to the React + Vite MVP lane unless P2 or a Phase-3 ADR overrides it explicitly."'
    )
    lines.append(
        '  - "只有当 Phase-2 提供了显式 auth-vendor contract 时，外部 IdP / OIDC 集成才算冻结；否则 P3 仅保持真实认证边界，但不绑定具体提供商。"'
        if zh
        else '  - "External IdP / OIDC integration is only frozen when Phase-2 provides an explicit auth-vendor contract; otherwise P3 keeps the auth boundary real but provider-agnostic."'
    )
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate the Phase-3 tech-stack decision file")
    parser.add_argument("--esp", required=True)
    parser.add_argument("--stage-03", required=True)
    parser.add_argument("--stage-04", required=True)
    parser.add_argument("--title", default="Phase-3 Stack Decision")
    parser.add_argument("--output-locale", default=resolve_output_locale())
    parser.add_argument("--output", required=True)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    document = build_stack_decision_document(
        esp_text=Path(args.esp).resolve().read_text(encoding="utf-8"),
        stage_03_text=Path(args.stage_03).resolve().read_text(encoding="utf-8"),
        stage_04_text=Path(args.stage_04).resolve().read_text(encoding="utf-8"),
        title=args.title,
        output_locale=args.output_locale,
    )
    output_path = Path(args.output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(document, encoding="utf-8")
    print(json.dumps({"output": str(output_path)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
